{% set name = "Cheetah3" %}
{% set version = "3.2.6.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63157d7a00a273b59676b5be5aa817c75c37efc88478231f1a160f4cfb7f7878

build:
  number: 6
  # https://github.com/CheetahTemplate3/cheetah3/blob/3.2.5/SetupConfig.py#L83
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - Cheetah
    - Cheetah.Macros
    - Cheetah.Templates
    - Cheetah.Tests
    - Cheetah.Tools
    - Cheetah.Utils

about:
  home: https://cheetahtemplate.org/
  summary: Cheetah is a template engine and code generation tool
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/CheetahTemplate3/cheetah3

extra:
  recipe-maintainers:
    - pinin4fjords
    - nehaljwani
